config/routes.rb
SalaExtraccion::Application.routes.draw do

  root  to: "producers#index"
  
  resources :producers
  
  resources :drawer_conteiner_incomes

  resources :barrels_incomes

  resources :waxes

  resources :barrels

  resources :drawer_containers

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  # validations  
  validates :tare, :net_weight, :type, presence: true

  # associations
  belongs_to :barrels_incomes
end

app/controllers/barrels_controller.rb
class BarrelsController < ApplicationController
  before_action :set_barrel, only: [:show, :edit, :update, :destroy]

  # GET /barrels
  # GET /barrels.json
  def index
    @barrels = Barrel.all
  end

  # GET /barrels/1
  # GET /barrels/1.json
  def show
  end

  # GET /barrels/new
  def new
    @barrel = Barrel.new
  end

  # GET /barrels/1/edit
  def edit
  end

  # POST /barrels
  # POST /barrels.json
  def create
    @barrel = Barrel.new(barrel_params)

    respond_to do |format|
      if @barrel.save
        format.html { redirect_to @barrel, notice: 'Barrel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @barrel }
      else
        format.html { render action: 'new' }
        format.json { render json: @barrel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barrels/1
  # PATCH/PUT /barrels/1.json
  def update
    respond_to do |format|
      if @barrel.update(barrel_params)
        format.html { redirect_to @barrel, notice: 'Barrel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @barrel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barrels/1
  # DELETE /barrels/1.json
  def destroy
    @barrel.destroy
    respond_to do |format|
      format.html { redirect_to barrels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrel
      @barrel = Barrel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barrel_params
      params.require(:barrel).permit(:type, :net_weight, :tare)
    end
end

app/helpers/barrels_helper.rb
module BarrelsHelper
end

app/views/barrels/_form.html.erb
<%= form_for(@barrel) do |f| %>
  <% if @barrel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barrel.errors.count, "error") %> prohibited this barrel from being saved:</h2>

      <ul>
      <% @barrel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :net_weight %><br>
    <%= f.text_field :net_weight %>
  </div>
  <div class="field">
    <%= f.label :tare %><br>
    <%= f.text_field :tare %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barrels/edit.html.erb
<h1>Editing barrel</h1>

<%= render 'form' %>

<%= link_to 'Show', @barrel %> |
<%= link_to 'Back', barrels_path %>

app/views/barrels/index.html.erb
<h1>Listing barrels</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Net weight</th>
      <th>Tare</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @barrels.each do |barrel| %>
      <tr>
        <td><%= barrel.type %></td>
        <td><%= barrel.net_weight %></td>
        <td><%= barrel.tare %></td>
        <td><%= link_to 'Show', barrel %></td>
        <td><%= link_to 'Edit', edit_barrel_path(barrel) %></td>
        <td><%= link_to 'Destroy', barrel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barrel', new_barrel_path %>

app/views/barrels/new.html.erb
<h1>New barrel</h1>

<%= render 'form' %>

<%= link_to 'Back', barrels_path %>

app/views/barrels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @barrel.type %>
</p>

<p>
  <strong>Net weight:</strong>
  <%= @barrel.net_weight %>
</p>

<p>
  <strong>Tare:</strong>
  <%= @barrel.tare %>
</p>

<%= link_to 'Edit', edit_barrel_path(@barrel) %> |
<%= link_to 'Back', barrels_path %>