config/routes.rb
SalaExtraccion::Application.routes.draw do

  root  to: "producers#index"
  
  resources :producers
  
  resources :drawer_conteiner_incomes

  resources :barrels_incomes

  resources :waxes

  resources :barrels

  resources :drawer_containers

end

app/models/wax.rb
class Wax < ActiveRecord::Base
  # validations
  validates :weight, presence: true

  # associations
  belongs_to :exit_movement, class_name: :movement
end

app/controllers/waxes_controller.rb
class WaxesController < ApplicationController
  before_action :set_wax, only: [:show, :edit, :update, :destroy]

  # GET /waxes
  # GET /waxes.json
  def index
    @waxes = Wax.all
  end

  # GET /waxes/1
  # GET /waxes/1.json
  def show
  end

  # GET /waxes/new
  def new
    @wax = Wax.new
  end

  # GET /waxes/1/edit
  def edit
  end

  # POST /waxes
  # POST /waxes.json
  def create
    @wax = Wax.new(wax_params)

    respond_to do |format|
      if @wax.save
        format.html { redirect_to @wax, notice: 'Wax was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wax }
      else
        format.html { render action: 'new' }
        format.json { render json: @wax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waxes/1
  # PATCH/PUT /waxes/1.json
  def update
    respond_to do |format|
      if @wax.update(wax_params)
        format.html { redirect_to @wax, notice: 'Wax was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waxes/1
  # DELETE /waxes/1.json
  def destroy
    @wax.destroy
    respond_to do |format|
      format.html { redirect_to waxes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wax
      @wax = Wax.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wax_params
      params.require(:wax).permit(:weight)
    end
end

app/helpers/waxes_helper.rb
module WaxesHelper
end

app/views/waxes/_form.html.erb
<%= form_for(@wax) do |f| %>
  <% if @wax.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wax.errors.count, "error") %> prohibited this wax from being saved:</h2>

      <ul>
      <% @wax.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waxes/edit.html.erb
<h1>Editing wax</h1>

<%= render 'form' %>

<%= link_to 'Show', @wax %> |
<%= link_to 'Back', waxes_path %>

app/views/waxes/index.html.erb
<h1>Listing waxes</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @waxes.each do |wax| %>
      <tr>
        <td><%= wax.weight %></td>
        <td><%= link_to 'Show', wax %></td>
        <td><%= link_to 'Edit', edit_wax_path(wax) %></td>
        <td><%= link_to 'Destroy', wax, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wax', new_wax_path %>

app/views/waxes/new.html.erb
<h1>New wax</h1>

<%= render 'form' %>

<%= link_to 'Back', waxes_path %>

app/views/waxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @wax.weight %>
</p>

<%= link_to 'Edit', edit_wax_path(@wax) %> |
<%= link_to 'Back', waxes_path %>