config/routes.rb
SalaExtraccion::Application.routes.draw do

  root  to: "producers#index"
  
  resources :producers
  
  resources :drawer_conteiner_incomes

  resources :barrels_incomes

  resources :waxes

  resources :barrels

  resources :drawer_containers

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  # validations
  validates :name, :last_name, :dni, :telephone, :renapa, :address, presence: true
  
  # associations 
  has_many :barrels_incomes, dependent: :destroy
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producer }
      else
        format.html { render action: 'new' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:dni, :name, :last_name, :telephone, :address, :renapa)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<div class="box-body">
  <%= form_for(@producer) do |f| %>
    <% if @producer.errors.any? %>
      <div class="row">
        <div class="col-md-6">
          <div class="box box-danger">
            <div class="box-header">
              <i class="fa fa-warning"></i>
              <h3 class="box-title">Alerts</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="alert alert-danger alert-dismissable">
                <h2><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

                <ul>
                <% @producer.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div> </div> </div> </div> </div> </div>
    <% end %>

    <div class="form-group">

      <label>Name</label>
      <div class="input-group">
          <input type="text" name="producer[name]" class="form-control"/>
      </div><!-- /.input group -->

      <label>Last Name</label>
      <div class="input-group">
          <input type="text" name="producer[last_name]" class="form-control"/>
      </div><!-- /.input group -->

      <label>Dni</label>
      <div class="input-group">
          <input type="text" name="producer[dni]" class="form-control"/>
      </div><!-- /.input group -->

      <label>Renapa</label>
      <div class="input-group">
          <input type="text" name="producer[renapa]" class="form-control"/>
      </div><!-- /.input group -->      
      
      <label>Telephone</label>
      <div class="input-group">
          <input type="text" name="producer[telephone]" class="form-control"/>
      </div><!-- /.input group -->

      <label>Address</label>
      <div class="input-group">
          <input type="text" name="producer[address]" class="form-control"/>
      </div><!-- /.input group --></br>
    
      <div class="box-footer">
        <button type="submit" name="commit" value="Create Producer" class="btn btn-primary">New Producer</button>
      </div> 
    </div>
  <% end %>
</div>

app/views/producers/edit.html.erb
<h1>Editing producer</h1>

<%= render 'form' %>

<%= link_to 'Show', @producer %> |
<%= link_to 'Back', producers_path %>

app/views/producers/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Listing Producers</h3>                                    
      </div><!-- /.box-header -->
      <div class="box-body table-responsive">
        <table id="example2" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Dni</th>
            <th>Name</th>
            <th>Last name</th>
            <th>Telephone</th>
            <th>Address</th>
            <th>Renapa</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @producers.each do |producer| %>
            <tr>
              <td><%= producer.dni %></td>
              <td><%= producer.name %></td>
              <td><%= producer.last_name %></td>
              <td><%= producer.telephone %></td>
              <td><%= producer.address %></td>
              <td><%= producer.renapa %></td>
              <td><%= link_to 'Show', producer %></td>
              <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
              <td><%= link_to 'Destroy', producer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <div class="box-footer">
        <%= link_to 'New Producer', new_producer_path, class:"btn btn-primary"%>
      </div>

    </div><!-- /.box-body -->
</div><!-- /.box -->

app/views/producers/new.html.erb
<h1>New producer</h1>

<%= render 'form' %>

<%= link_to 'Back', producers_path %>

app/views/producers/show.html.erb
<div class="box-body">
  <div class="row">
  <div class="col-md-6">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-warning"></i>
        <h3 class="box-title">Alerts</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="alert alert-success alert-dismissable">
          <p id="notice"><%= notice %></p>
        </div> 
      </div> 
    </div> 
  </div> 
  </div>

<p>
  <strong>Dni:</strong>
  <%= @producer.dni %>
</p>

<p>
  <strong>Name:</strong>
  <%= @producer.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @producer.last_name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @producer.telephone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @producer.address %>
</p>

<p>
  <strong>Renapa:</strong>
  <%= @producer.renapa %>
</p>

<%= link_to 'Edit', edit_producer_path(@producer) %> |
<%= link_to 'Back', producers_path %>