config/routes.rb
SalaExtraccion::Application.routes.draw do

  root  to: "producers#index"
  
  resources :producers
  
  resources :drawer_conteiner_incomes

  resources :barrels_incomes

  resources :waxes

  resources :barrels

  resources :drawer_containers

end

app/models/barrel.rb
class Barrel < ActiveRecord::Base
  # validations  
  validates :tare, :net_weight, :type, presence: true

  # associations
  belongs_to :barrels_incomes
end

app/models/barrels_income.rb
class BarrelsIncome < ActiveRecord::Base

	# validations
  validates :nro_remit, :producer_id, presence: true
	  
  # associations
  belongs_to :producer
  has_many :barrels
end

app/models/drawer_container.rb
class DrawerContainer < ActiveRecord::Base
  # validations
  validates :drawers, presence: true

  # associations
  belongs_to :drawerconteiner_incomes
end

app/models/drawer_conteiner_income.rb
class DrawerConteinerIncome < ActiveRecord::Base
  # validations
  validates :nro_remit, :producer_id, presence: true

  #association
  belongs_to :producer
  has_one :drawer_container

end

app/models/entrance_barrel.rb
class EntranceBarrel
  # this class should have the logic to do an entrance barrels
  # create the EntranceMovement and that stuff..

  def initialize(producer, barrels)
    # we should recieve Producer, Barrels
    # maybe is the hash that we recieve from POST /entrance_movement (barrels)
    @producer = producer
    @barrels = barrels
  end

  def save
    # here we must be aware of Exceptions
    # we MUST return a boolean. This'll be used in the controller
    begin
      entrance_movement = EntranceMovement.new(producer: @producer,
                                               nro_remit: EntrnaceMovement.next_nro_remit,
                                               barrels: @barrels)
      entrance_movement.save!
    rescue Exception => e
      # log this
      false
    end
  end
end

app/models/entrance_movement.rb
class EntranceMovement < Movement
end

app/models/exit_movement.rb
class ExitMovement < Movement
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  # validations
  validates :nro_remit, :producer_id, presence: true

  # associations
  belongs_to :producer
  has_one :drawer_container
  has_one :wax
  has_and_belongs_to_many :barrels
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  # validations
  validates :name, :last_name, :dni, :telephone, :renapa, :address, presence: true
  
  # associations 
  has_many :barrels_incomes, dependent: :destroy
end

app/models/wax.rb
class Wax < ActiveRecord::Base
  # validations
  validates :weight, presence: true

  # associations
  belongs_to :exit_movement, class_name: :movement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/barrels_controller.rb
class BarrelsController < ApplicationController
  before_action :set_barrel, only: [:show, :edit, :update, :destroy]

  # GET /barrels
  # GET /barrels.json
  def index
    @barrels = Barrel.all
  end

  # GET /barrels/1
  # GET /barrels/1.json
  def show
  end

  # GET /barrels/new
  def new
    @barrel = Barrel.new
  end

  # GET /barrels/1/edit
  def edit
  end

  # POST /barrels
  # POST /barrels.json
  def create
    @barrel = Barrel.new(barrel_params)

    respond_to do |format|
      if @barrel.save
        format.html { redirect_to @barrel, notice: 'Barrel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @barrel }
      else
        format.html { render action: 'new' }
        format.json { render json: @barrel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barrels/1
  # PATCH/PUT /barrels/1.json
  def update
    respond_to do |format|
      if @barrel.update(barrel_params)
        format.html { redirect_to @barrel, notice: 'Barrel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @barrel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barrels/1
  # DELETE /barrels/1.json
  def destroy
    @barrel.destroy
    respond_to do |format|
      format.html { redirect_to barrels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrel
      @barrel = Barrel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barrel_params
      params.require(:barrel).permit(:type, :net_weight, :tare)
    end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producer }
      else
        format.html { render action: 'new' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:dni, :name, :last_name, :telephone, :address, :renapa)
    end
end

app/controllers/waxes_controller.rb
class WaxesController < ApplicationController
  before_action :set_wax, only: [:show, :edit, :update, :destroy]

  # GET /waxes
  # GET /waxes.json
  def index
    @waxes = Wax.all
  end

  # GET /waxes/1
  # GET /waxes/1.json
  def show
  end

  # GET /waxes/new
  def new
    @wax = Wax.new
  end

  # GET /waxes/1/edit
  def edit
  end

  # POST /waxes
  # POST /waxes.json
  def create
    @wax = Wax.new(wax_params)

    respond_to do |format|
      if @wax.save
        format.html { redirect_to @wax, notice: 'Wax was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wax }
      else
        format.html { render action: 'new' }
        format.json { render json: @wax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waxes/1
  # PATCH/PUT /waxes/1.json
  def update
    respond_to do |format|
      if @wax.update(wax_params)
        format.html { redirect_to @wax, notice: 'Wax was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waxes/1
  # DELETE /waxes/1.json
  def destroy
    @wax.destroy
    respond_to do |format|
      format.html { redirect_to waxes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wax
      @wax = Wax.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wax_params
      params.require(:wax).permit(:weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barrels_helper.rb
module BarrelsHelper
end

app/helpers/barrels_incomes_helper.rb
module BarrelsIncomesHelper
end

app/helpers/drawer_containers_helper.rb
module DrawerContainersHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/waxes_helper.rb
module WaxesHelper
end

app/views/layouts/_main.html.erb
<div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
  <aside class="left-side sidebar-offcanvas">
      <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <ul class="sidebar-menu">
        <li>
          <%= link_to 'Producers', producers_path %>
        </li>
        <li>
            <%= link_to 'Barrels', barrels_path %>
        </li>
        <li>
            <%= link_to 'Drawers', drawer_containers_path %>
        </li>
        <li>
            <%= link_to 'Wax', waxes_path %>
        </li>
        <li>
            <%= link_to 'Incomes', '#' %>
        </li>
      </ul>
    </section>
                <!-- /.sidebar -->
  </aside>

  <aside class="right-side">
    <section class="content-header">
    </section>
    <!-- Main content -->
    <section class="content">
      <%= yield %>
    </section><!-- /.content -->
  </aside><!-- /.right-side -->
</div><!-- ./wrapper -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<%= link_to 'Home', root_path, class: 'logo' %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sala Extraccion" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sala Extraccion" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "main" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="skin-black">
    <header class="header">
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/main' %>
  </body>
</html>